/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *alignment2;
  GtkWidget *vbox1;
  GtkWidget *vbox8;
  GtkWidget *hbox2;
  GtkWidget *vbox19;
  GtkWidget *vbox24;
  GtkWidget *hbox13;
  GtkWidget *vbox24_2;
  GtkWidget *hbox14;
  GtkWidget *in_trim_scale;
  GtkWidget *inmeter;
  GtkWidget *label61;
  GtkWidget *vbox78;
  GtkWidget *notebook1;
  GtkWidget *hbox21;
  GtkWidget *eqb_hbox;
  GtkWidget *vbox41;
  GtkWidget *eqb1;
  GtkWidget *label131;
  GtkWidget *vbox42;
  GtkWidget *vbox52;
  GtkWidget *eqb2;
  GtkWidget *label132;
  GtkWidget *vbox43;
  GtkWidget *vbox53;
  GtkWidget *eqb3;
  GtkWidget *label133;
  GtkWidget *vbox44;
  GtkWidget *vbox54;
  GtkWidget *eqb4;
  GtkWidget *label134;
  GtkWidget *vbox45;
  GtkWidget *vbox55;
  GtkWidget *eqb5;
  GtkWidget *label135;
  GtkWidget *vbox46;
  GtkWidget *vbox56;
  GtkWidget *eqb6;
  GtkWidget *label136;
  GtkWidget *vbox47;
  GtkWidget *vbox57;
  GtkWidget *eqb7;
  GtkWidget *label137;
  GtkWidget *vbox48;
  GtkWidget *vbox58;
  GtkWidget *eqb8;
  GtkWidget *label138;
  GtkWidget *vbox50;
  GtkWidget *vbox59;
  GtkWidget *eqb9;
  GtkWidget *label139;
  GtkWidget *vbox49;
  GtkWidget *vbox60;
  GtkWidget *eqb10;
  GtkWidget *label140;
  GtkWidget *vbox51;
  GtkWidget *vbox61;
  GtkWidget *eqb11;
  GtkWidget *label141;
  GtkWidget *vbox62;
  GtkWidget *eqb12;
  GtkWidget *label142;
  GtkWidget *vbox63;
  GtkWidget *eqb13;
  GtkWidget *label143;
  GtkWidget *vbox64;
  GtkWidget *eqb14;
  GtkWidget *label144;
  GtkWidget *vbox65;
  GtkWidget *eqb15;
  GtkWidget *label145;
  GtkWidget *vbox66;
  GtkWidget *eqb16;
  GtkWidget *label146;
  GtkWidget *vbox67;
  GtkWidget *eqb17;
  GtkWidget *label147;
  GtkWidget *vbox68;
  GtkWidget *eqb18;
  GtkWidget *label148;
  GtkWidget *vbox69;
  GtkWidget *eqb19;
  GtkWidget *label149;
  GtkWidget *vbox70;
  GtkWidget *eqb20;
  GtkWidget *label150;
  GtkWidget *vbox71;
  GtkWidget *eqb21;
  GtkWidget *label151;
  GtkWidget *vbox72;
  GtkWidget *eqb22;
  GtkWidget *label152;
  GtkWidget *vbox73;
  GtkWidget *eqb23;
  GtkWidget *label153;
  GtkWidget *vbox74;
  GtkWidget *eqb24;
  GtkWidget *label154;
  GtkWidget *vbox75;
  GtkWidget *eqb25;
  GtkWidget *label155;
  GtkWidget *vbox76;
  GtkWidget *eqb26;
  GtkWidget *label156;
  GtkWidget *vbox77;
  GtkWidget *eqb27;
  GtkWidget *label157;
  GtkWidget *vbox80;
  GtkWidget *eqb28;
  GtkWidget *label158;
  GtkWidget *label47;
  GtkWidget *empty_notebook_page;
  GtkWidget *label48;
  GtkWidget *label49;
  GtkWidget *label78;
  GtkWidget *cross_lbl;
  GtkWidget *low2mid;
  GtkWidget *mid2high;
  GtkWidget *alignment1;
  GtkWidget *eventbox1;
  GtkWidget *vbox11;
  GtkWidget *frame2;
  GtkWidget *vbox25;
  GtkWidget *hbox15;
  GtkWidget *hseparator3;
  GtkWidget *label62;
  GtkWidget *hseparator4;
  GtkWidget *hbox1;
  GtkWidget *frame7;
  GtkWidget *low_comp;
  GtkWidget *vbox30;
  GtkWidget *table8;
  GtkWidget *label71;
  GtkWidget *label72;
  GtkWidget *label73;
  GtkWidget *vscale34;
  GtkWidget *vscale35;
  GtkWidget *vscale36;
  GtkWidget *vscale37;
  GtkWidget *vbox31;
  GtkWidget *vscale38;
  GtkWidget *label75;
  GtkWidget *vscale39;
  GtkWidget *label70;
  GtkWidget *label74;
  GtkWidget *table9;
  GtkWidget *progressbar15;
  GtkWidget *label76;
  GtkWidget *label77;
  GtkWidget *progressbar14;
  GtkWidget *label_Low;
  GtkWidget *frame8;
  GtkWidget *mid_comp;
  GtkWidget *vbox36;
  GtkWidget *table12;
  GtkWidget *label86;
  GtkWidget *label87;
  GtkWidget *label88;
  GtkWidget *label89;
  GtkWidget *vscale43;
  GtkWidget *vscale44;
  GtkWidget *vscale45;
  GtkWidget *vscale46;
  GtkWidget *vbox37;
  GtkWidget *vscale47;
  GtkWidget *label91;
  GtkWidget *vscale48;
  GtkWidget *label90;
  GtkWidget *table13;
  GtkWidget *progressbar22;
  GtkWidget *label92;
  GtkWidget *label93;
  GtkWidget *progressbar23;
  GtkWidget *label94;
  GtkWidget *frame6;
  GtkWidget *high_comp;
  GtkWidget *vbox18;
  GtkWidget *table6;
  GtkWidget *label22;
  GtkWidget *label23;
  GtkWidget *label24;
  GtkWidget *label25;
  GtkWidget *vscale18;
  GtkWidget *vscale19;
  GtkWidget *vscale20;
  GtkWidget *vscale21;
  GtkWidget *vbox7;
  GtkWidget *vscale22;
  GtkWidget *label27;
  GtkWidget *vscale23;
  GtkWidget *label26;
  GtkWidget *table11;
  GtkWidget *progressbar20;
  GtkWidget *label84;
  GtkWidget *label85;
  GtkWidget *progressbar21;
  GtkWidget *label68;
  GtkWidget *hbox7;
  GtkWidget *curve1;
  GtkWidget *vbox15;
  GtkWidget *vbox12;
  GtkWidget *hbox8;
  GtkWidget *hbox_bottom_r;
  GtkWidget *frame3;
  GtkWidget *vbox23;
  GtkWidget *vbox_limiter;
  GtkWidget *hbox3;
  GtkWidget *hbox16;
  GtkWidget *hseparator5;
  GtkWidget *label63;
  GtkWidget *hseparator6;
  GtkWidget *hbox10;
  GtkWidget *vbox32;
  GtkWidget *label79;
  GtkWidget *hbox17;
  GtkWidget *vscale40;
  GtkWidget *progressbar16;
  GtkWidget *vbox33;
  GtkWidget *label80;
  GtkWidget *hbox18;
  GtkWidget *vscale41;
  GtkWidget *vbox34;
  GtkWidget *label81;
  GtkWidget *hbox19;
  GtkWidget *vscale42;
  GtkWidget *progressbar17;
  GtkWidget *vbuttonbox1;
  GtkWidget *button8;
  GtkWidget *button9;
  GtkWidget *button10;
  GtkWidget *quit;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (window1, "window1");
  gtk_widget_set_size_request (window1, 750, 650);
  GTK_WIDGET_SET_FLAGS (window1, GTK_CAN_FOCUS);
  gtk_window_set_title (GTK_WINDOW (window1), _("JAM"));
  gtk_window_set_default_size (GTK_WINDOW (window1), 750, -1);

  alignment2 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment2, "alignment2");
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (window1), alignment2);
  gtk_widget_set_size_request (alignment2, 715, -2);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox1, "vbox1");
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (alignment2), vbox1);
  gtk_widget_set_size_request (vbox1, 715, 600);

  vbox8 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox8, "vbox8");
  gtk_widget_show (vbox8);
  gtk_box_pack_start (GTK_BOX (vbox1), vbox8, FALSE, FALSE, 0);
  gtk_widget_set_size_request (vbox8, -2, 250);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox2, "hbox2");
  gtk_widget_show (hbox2);
  gtk_box_pack_start (GTK_BOX (vbox8), hbox2, FALSE, TRUE, 0);

  vbox19 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox19, "vbox19");
  gtk_widget_show (vbox19);
  gtk_box_pack_start (GTK_BOX (hbox2), vbox19, TRUE, TRUE, 0);

  vbox24 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox24, "vbox24");
  gtk_widget_show (vbox24);
  gtk_box_pack_start (GTK_BOX (vbox19), vbox24, FALSE, TRUE, 0);

  hbox13 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox13, "hbox13");
  gtk_widget_show (hbox13);
  gtk_box_pack_start (GTK_BOX (vbox24), hbox13, TRUE, TRUE, 0);

  vbox24_2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox24_2, "vbox24_2");
  gtk_widget_show (vbox24_2);
  gtk_box_pack_start (GTK_BOX (hbox13), vbox24_2, TRUE, TRUE, 1);
  gtk_widget_set_size_request (vbox24_2, 2, -2);

  hbox14 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox14, "hbox14");
  gtk_widget_show (hbox14);
  gtk_box_pack_start (GTK_BOX (vbox24_2), hbox14, TRUE, TRUE, 5);
  gtk_widget_set_size_request (hbox14, 15, -2);

  in_trim_scale = gtk_vscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -12, 0, 1, 6, 0)));
  gtk_widget_set_name (in_trim_scale, "in_trim_scale");
  gtk_widget_show (in_trim_scale);
  gtk_box_pack_start (GTK_BOX (hbox14), in_trim_scale, TRUE, TRUE, 0);
  gtk_widget_set_size_request (in_trim_scale, 20, -2);
  gtk_range_set_inverted (GTK_RANGE (in_trim_scale), TRUE);

  inmeter = gtk_progress_bar_new ();
  gtk_widget_set_name (inmeter, "inmeter");
  gtk_widget_show (inmeter);
  gtk_box_pack_start (GTK_BOX (hbox14), inmeter, TRUE, FALSE, 0);
  gtk_widget_set_size_request (inmeter, 20, -2);
  gtk_progress_bar_set_orientation (GTK_PROGRESS_BAR (inmeter), GTK_PROGRESS_BOTTOM_TO_TOP);

  label61 = gtk_label_new (_("Input"));
  gtk_widget_set_name (label61, "label61");
  gtk_widget_show (label61);
  gtk_box_pack_start (GTK_BOX (vbox24_2), label61, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label61, 2, -2);
  gtk_label_set_justify (GTK_LABEL (label61), GTK_JUSTIFY_LEFT);

  vbox78 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox78, "vbox78");
  gtk_widget_show (vbox78);
  gtk_box_pack_start (GTK_BOX (hbox13), vbox78, TRUE, TRUE, 4);

  notebook1 = gtk_notebook_new ();
  gtk_widget_set_name (notebook1, "notebook1");
  gtk_widget_show (notebook1);
  gtk_box_pack_start (GTK_BOX (vbox78), notebook1, TRUE, TRUE, 0);
  gtk_widget_set_size_request (notebook1, 600, 192);

  hbox21 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox21, "hbox21");
  gtk_widget_show (hbox21);
  gtk_container_add (GTK_CONTAINER (notebook1), hbox21);

  eqb_hbox = gtk_hbox_new (TRUE, 0);
  gtk_widget_set_name (eqb_hbox, "eqb_hbox");
  gtk_widget_show (eqb_hbox);
  gtk_box_pack_start (GTK_BOX (hbox21), eqb_hbox, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (eqb_hbox), 1);

  vbox41 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox41, "vbox41");
  gtk_widget_show (vbox41);
  gtk_box_pack_start (GTK_BOX (eqb_hbox), vbox41, TRUE, TRUE, 0);

  eqb1 = gtk_vscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -70, 24, 1, 6, 0)));
  gtk_widget_set_name (eqb1, "eqb1");
  gtk_widget_show (eqb1);
  gtk_box_pack_start (GTK_BOX (vbox41), eqb1, TRUE, TRUE, 0);
  gtk_scale_set_digits (GTK_SCALE (eqb1), 0);
  gtk_range_set_inverted (GTK_RANGE (eqb1), TRUE);

  label131 = gtk_label_new (_("25"));
  gtk_widget_set_name (label131, "label131");
  gtk_widget_show (label131);
  gtk_box_pack_start (GTK_BOX (vbox41), label131, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label131), GTK_JUSTIFY_LEFT);

  vbox42 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox42, "vbox42");
  gtk_widget_show (vbox42);
  gtk_box_pack_start (GTK_BOX (eqb_hbox), vbox42, TRUE, TRUE, 0);

  vbox52 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox52, "vbox52");
  gtk_widget_show (vbox52);
  gtk_box_pack_start (GTK_BOX (vbox42), vbox52, TRUE, TRUE, 0);

  eqb2 = gtk_vscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -70, 24, 1, 6, 0)));
  gtk_widget_set_name (eqb2, "eqb2");
  gtk_widget_show (eqb2);
  gtk_box_pack_start (GTK_BOX (vbox52), eqb2, TRUE, TRUE, 0);
  gtk_scale_set_digits (GTK_SCALE (eqb2), 0);
  gtk_range_set_inverted (GTK_RANGE (eqb2), TRUE);

  label132 = gtk_label_new (_("31"));
  gtk_widget_set_name (label132, "label132");
  gtk_widget_show (label132);
  gtk_box_pack_start (GTK_BOX (vbox52), label132, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label132), GTK_JUSTIFY_LEFT);

  vbox43 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox43, "vbox43");
  gtk_widget_show (vbox43);
  gtk_box_pack_start (GTK_BOX (eqb_hbox), vbox43, TRUE, TRUE, 0);

  vbox53 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox53, "vbox53");
  gtk_widget_show (vbox53);
  gtk_box_pack_start (GTK_BOX (vbox43), vbox53, TRUE, TRUE, 0);

  eqb3 = gtk_vscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -70, 24, 1, 6, 0)));
  gtk_widget_set_name (eqb3, "eqb3");
  gtk_widget_show (eqb3);
  gtk_box_pack_start (GTK_BOX (vbox53), eqb3, TRUE, TRUE, 0);
  gtk_scale_set_digits (GTK_SCALE (eqb3), 0);
  gtk_range_set_inverted (GTK_RANGE (eqb3), TRUE);

  label133 = gtk_label_new (_("39"));
  gtk_widget_set_name (label133, "label133");
  gtk_widget_show (label133);
  gtk_box_pack_start (GTK_BOX (vbox53), label133, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label133), GTK_JUSTIFY_LEFT);

  vbox44 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox44, "vbox44");
  gtk_widget_show (vbox44);
  gtk_box_pack_start (GTK_BOX (eqb_hbox), vbox44, TRUE, TRUE, 0);

  vbox54 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox54, "vbox54");
  gtk_widget_show (vbox54);
  gtk_box_pack_start (GTK_BOX (vbox44), vbox54, TRUE, TRUE, 0);

  eqb4 = gtk_vscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -70, 24, 1, 6, 0)));
  gtk_widget_set_name (eqb4, "eqb4");
  gtk_widget_show (eqb4);
  gtk_box_pack_start (GTK_BOX (vbox54), eqb4, TRUE, TRUE, 0);
  gtk_scale_set_digits (GTK_SCALE (eqb4), 0);
  gtk_range_set_inverted (GTK_RANGE (eqb4), TRUE);

  label134 = gtk_label_new (_("50"));
  gtk_widget_set_name (label134, "label134");
  gtk_widget_show (label134);
  gtk_box_pack_start (GTK_BOX (vbox54), label134, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label134), GTK_JUSTIFY_LEFT);

  vbox45 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox45, "vbox45");
  gtk_widget_show (vbox45);
  gtk_box_pack_start (GTK_BOX (eqb_hbox), vbox45, TRUE, TRUE, 0);

  vbox55 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox55, "vbox55");
  gtk_widget_show (vbox55);
  gtk_box_pack_start (GTK_BOX (vbox45), vbox55, TRUE, TRUE, 0);

  eqb5 = gtk_vscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -70, 24, 1, 6, 0)));
  gtk_widget_set_name (eqb5, "eqb5");
  gtk_widget_show (eqb5);
  gtk_box_pack_start (GTK_BOX (vbox55), eqb5, TRUE, TRUE, 0);
  gtk_scale_set_digits (GTK_SCALE (eqb5), 0);
  gtk_range_set_inverted (GTK_RANGE (eqb5), TRUE);

  label135 = gtk_label_new (_("62"));
  gtk_widget_set_name (label135, "label135");
  gtk_widget_show (label135);
  gtk_box_pack_start (GTK_BOX (vbox55), label135, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label135), GTK_JUSTIFY_LEFT);

  vbox46 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox46, "vbox46");
  gtk_widget_show (vbox46);
  gtk_box_pack_start (GTK_BOX (eqb_hbox), vbox46, TRUE, TRUE, 0);

  vbox56 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox56, "vbox56");
  gtk_widget_show (vbox56);
  gtk_box_pack_start (GTK_BOX (vbox46), vbox56, TRUE, TRUE, 0);

  eqb6 = gtk_vscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -70, 24, 1, 6, 0)));
  gtk_widget_set_name (eqb6, "eqb6");
  gtk_widget_show (eqb6);
  gtk_box_pack_start (GTK_BOX (vbox56), eqb6, TRUE, TRUE, 0);
  gtk_scale_set_digits (GTK_SCALE (eqb6), 0);
  gtk_range_set_inverted (GTK_RANGE (eqb6), TRUE);

  label136 = gtk_label_new (_("79"));
  gtk_widget_set_name (label136, "label136");
  gtk_widget_show (label136);
  gtk_box_pack_start (GTK_BOX (vbox56), label136, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label136), GTK_JUSTIFY_LEFT);

  vbox47 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox47, "vbox47");
  gtk_widget_show (vbox47);
  gtk_box_pack_start (GTK_BOX (eqb_hbox), vbox47, TRUE, TRUE, 0);

  vbox57 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox57, "vbox57");
  gtk_widget_show (vbox57);
  gtk_box_pack_start (GTK_BOX (vbox47), vbox57, TRUE, TRUE, 0);

  eqb7 = gtk_vscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -70, 24, 1, 6, 0)));
  gtk_widget_set_name (eqb7, "eqb7");
  gtk_widget_show (eqb7);
  gtk_box_pack_start (GTK_BOX (vbox57), eqb7, TRUE, TRUE, 0);
  gtk_scale_set_digits (GTK_SCALE (eqb7), 0);
  gtk_range_set_inverted (GTK_RANGE (eqb7), TRUE);

  label137 = gtk_label_new (_("100"));
  gtk_widget_set_name (label137, "label137");
  gtk_widget_show (label137);
  gtk_box_pack_start (GTK_BOX (vbox57), label137, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label137), GTK_JUSTIFY_LEFT);

  vbox48 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox48, "vbox48");
  gtk_widget_show (vbox48);
  gtk_box_pack_start (GTK_BOX (eqb_hbox), vbox48, TRUE, TRUE, 0);

  vbox58 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox58, "vbox58");
  gtk_widget_show (vbox58);
  gtk_box_pack_start (GTK_BOX (vbox48), vbox58, TRUE, TRUE, 0);

  eqb8 = gtk_vscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -70, 24, 1, 6, 0)));
  gtk_widget_set_name (eqb8, "eqb8");
  gtk_widget_show (eqb8);
  gtk_box_pack_start (GTK_BOX (vbox58), eqb8, TRUE, TRUE, 0);
  gtk_scale_set_digits (GTK_SCALE (eqb8), 0);
  gtk_range_set_inverted (GTK_RANGE (eqb8), TRUE);

  label138 = gtk_label_new (_("125"));
  gtk_widget_set_name (label138, "label138");
  gtk_widget_show (label138);
  gtk_box_pack_start (GTK_BOX (vbox58), label138, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label138), GTK_JUSTIFY_LEFT);

  vbox50 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox50, "vbox50");
  gtk_widget_show (vbox50);
  gtk_box_pack_start (GTK_BOX (eqb_hbox), vbox50, TRUE, TRUE, 0);

  vbox59 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox59, "vbox59");
  gtk_widget_show (vbox59);
  gtk_box_pack_start (GTK_BOX (vbox50), vbox59, TRUE, TRUE, 0);

  eqb9 = gtk_vscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -70, 24, 1, 6, 0)));
  gtk_widget_set_name (eqb9, "eqb9");
  gtk_widget_show (eqb9);
  gtk_box_pack_start (GTK_BOX (vbox59), eqb9, TRUE, TRUE, 0);
  gtk_scale_set_digits (GTK_SCALE (eqb9), 0);
  gtk_range_set_inverted (GTK_RANGE (eqb9), TRUE);

  label139 = gtk_label_new (_("158"));
  gtk_widget_set_name (label139, "label139");
  gtk_widget_show (label139);
  gtk_box_pack_start (GTK_BOX (vbox59), label139, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label139), GTK_JUSTIFY_LEFT);

  vbox49 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox49, "vbox49");
  gtk_widget_show (vbox49);
  gtk_box_pack_start (GTK_BOX (eqb_hbox), vbox49, TRUE, TRUE, 0);

  vbox60 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox60, "vbox60");
  gtk_widget_show (vbox60);
  gtk_box_pack_start (GTK_BOX (vbox49), vbox60, TRUE, TRUE, 0);

  eqb10 = gtk_vscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -70, 24, 1, 6, 0)));
  gtk_widget_set_name (eqb10, "eqb10");
  gtk_widget_show (eqb10);
  gtk_box_pack_start (GTK_BOX (vbox60), eqb10, TRUE, TRUE, 0);
  gtk_scale_set_digits (GTK_SCALE (eqb10), 0);
  gtk_range_set_inverted (GTK_RANGE (eqb10), TRUE);

  label140 = gtk_label_new (_("200"));
  gtk_widget_set_name (label140, "label140");
  gtk_widget_show (label140);
  gtk_box_pack_start (GTK_BOX (vbox60), label140, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label140), GTK_JUSTIFY_LEFT);

  vbox51 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox51, "vbox51");
  gtk_widget_show (vbox51);
  gtk_box_pack_start (GTK_BOX (eqb_hbox), vbox51, TRUE, TRUE, 0);

  vbox61 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox61, "vbox61");
  gtk_widget_show (vbox61);
  gtk_box_pack_start (GTK_BOX (vbox51), vbox61, TRUE, TRUE, 0);

  eqb11 = gtk_vscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -70, 24, 1, 6, 0)));
  gtk_widget_set_name (eqb11, "eqb11");
  gtk_widget_show (eqb11);
  gtk_box_pack_start (GTK_BOX (vbox61), eqb11, TRUE, TRUE, 0);
  gtk_scale_set_digits (GTK_SCALE (eqb11), 0);
  gtk_range_set_inverted (GTK_RANGE (eqb11), TRUE);

  label141 = gtk_label_new (_("251"));
  gtk_widget_set_name (label141, "label141");
  gtk_widget_show (label141);
  gtk_box_pack_start (GTK_BOX (vbox61), label141, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label141), GTK_JUSTIFY_LEFT);

  vbox62 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox62, "vbox62");
  gtk_widget_show (vbox62);
  gtk_box_pack_start (GTK_BOX (eqb_hbox), vbox62, TRUE, TRUE, 0);

  eqb12 = gtk_vscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -70, 24, 1, 6, 0)));
  gtk_widget_set_name (eqb12, "eqb12");
  gtk_widget_show (eqb12);
  gtk_box_pack_start (GTK_BOX (vbox62), eqb12, TRUE, TRUE, 0);
  gtk_scale_set_digits (GTK_SCALE (eqb12), 0);
  gtk_range_set_inverted (GTK_RANGE (eqb12), TRUE);

  label142 = gtk_label_new (_("317"));
  gtk_widget_set_name (label142, "label142");
  gtk_widget_show (label142);
  gtk_box_pack_start (GTK_BOX (vbox62), label142, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label142), GTK_JUSTIFY_LEFT);

  vbox63 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox63, "vbox63");
  gtk_widget_show (vbox63);
  gtk_box_pack_start (GTK_BOX (eqb_hbox), vbox63, TRUE, TRUE, 0);

  eqb13 = gtk_vscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -70, 24, 1, 6, 0)));
  gtk_widget_set_name (eqb13, "eqb13");
  gtk_widget_show (eqb13);
  gtk_box_pack_start (GTK_BOX (vbox63), eqb13, TRUE, TRUE, 0);
  gtk_scale_set_digits (GTK_SCALE (eqb13), 0);
  gtk_range_set_inverted (GTK_RANGE (eqb13), TRUE);

  label143 = gtk_label_new (_("400"));
  gtk_widget_set_name (label143, "label143");
  gtk_widget_show (label143);
  gtk_box_pack_start (GTK_BOX (vbox63), label143, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label143), GTK_JUSTIFY_LEFT);

  vbox64 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox64, "vbox64");
  gtk_widget_show (vbox64);
  gtk_box_pack_start (GTK_BOX (eqb_hbox), vbox64, TRUE, TRUE, 0);

  eqb14 = gtk_vscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -70, 24, 1, 6, 0)));
  gtk_widget_set_name (eqb14, "eqb14");
  gtk_widget_show (eqb14);
  gtk_box_pack_start (GTK_BOX (vbox64), eqb14, TRUE, TRUE, 0);
  gtk_scale_set_digits (GTK_SCALE (eqb14), 0);
  gtk_range_set_inverted (GTK_RANGE (eqb14), TRUE);

  label144 = gtk_label_new (_("503"));
  gtk_widget_set_name (label144, "label144");
  gtk_widget_show (label144);
  gtk_box_pack_start (GTK_BOX (vbox64), label144, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label144), GTK_JUSTIFY_LEFT);

  vbox65 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox65, "vbox65");
  gtk_widget_show (vbox65);
  gtk_box_pack_start (GTK_BOX (eqb_hbox), vbox65, TRUE, TRUE, 0);

  eqb15 = gtk_vscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -70, 24, 1, 6, 0)));
  gtk_widget_set_name (eqb15, "eqb15");
  gtk_widget_show (eqb15);
  gtk_box_pack_start (GTK_BOX (vbox65), eqb15, TRUE, TRUE, 0);
  gtk_scale_set_digits (GTK_SCALE (eqb15), 0);
  gtk_range_set_inverted (GTK_RANGE (eqb15), TRUE);

  label145 = gtk_label_new (_("634"));
  gtk_widget_set_name (label145, "label145");
  gtk_widget_show (label145);
  gtk_box_pack_start (GTK_BOX (vbox65), label145, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label145), GTK_JUSTIFY_LEFT);

  vbox66 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox66, "vbox66");
  gtk_widget_show (vbox66);
  gtk_box_pack_start (GTK_BOX (eqb_hbox), vbox66, TRUE, TRUE, 0);

  eqb16 = gtk_vscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -70, 24, 1, 6, 0)));
  gtk_widget_set_name (eqb16, "eqb16");
  gtk_widget_show (eqb16);
  gtk_box_pack_start (GTK_BOX (vbox66), eqb16, TRUE, TRUE, 0);
  gtk_scale_set_digits (GTK_SCALE (eqb16), 0);
  gtk_range_set_inverted (GTK_RANGE (eqb16), TRUE);

  label146 = gtk_label_new (_("800"));
  gtk_widget_set_name (label146, "label146");
  gtk_widget_show (label146);
  gtk_box_pack_start (GTK_BOX (vbox66), label146, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label146), GTK_JUSTIFY_LEFT);

  vbox67 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox67, "vbox67");
  gtk_widget_show (vbox67);
  gtk_box_pack_start (GTK_BOX (eqb_hbox), vbox67, TRUE, TRUE, 0);

  eqb17 = gtk_vscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -70, 24, 1, 6, 0)));
  gtk_widget_set_name (eqb17, "eqb17");
  gtk_widget_show (eqb17);
  gtk_box_pack_start (GTK_BOX (vbox67), eqb17, TRUE, TRUE, 0);
  gtk_scale_set_digits (GTK_SCALE (eqb17), 0);
  gtk_range_set_inverted (GTK_RANGE (eqb17), TRUE);

  label147 = gtk_label_new (_("1K"));
  gtk_widget_set_name (label147, "label147");
  gtk_widget_show (label147);
  gtk_box_pack_start (GTK_BOX (vbox67), label147, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label147), GTK_JUSTIFY_LEFT);

  vbox68 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox68, "vbox68");
  gtk_widget_show (vbox68);
  gtk_box_pack_start (GTK_BOX (eqb_hbox), vbox68, TRUE, TRUE, 0);

  eqb18 = gtk_vscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -70, 24, 1, 6, 0)));
  gtk_widget_set_name (eqb18, "eqb18");
  gtk_widget_show (eqb18);
  gtk_box_pack_start (GTK_BOX (vbox68), eqb18, TRUE, TRUE, 0);
  gtk_scale_set_digits (GTK_SCALE (eqb18), 0);
  gtk_range_set_inverted (GTK_RANGE (eqb18), TRUE);

  label148 = gtk_label_new (_("1K2"));
  gtk_widget_set_name (label148, "label148");
  gtk_widget_show (label148);
  gtk_box_pack_start (GTK_BOX (vbox68), label148, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label148), GTK_JUSTIFY_LEFT);

  vbox69 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox69, "vbox69");
  gtk_widget_show (vbox69);
  gtk_box_pack_start (GTK_BOX (eqb_hbox), vbox69, TRUE, TRUE, 0);

  eqb19 = gtk_vscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -70, 24, 1, 6, 0)));
  gtk_widget_set_name (eqb19, "eqb19");
  gtk_widget_show (eqb19);
  gtk_box_pack_start (GTK_BOX (vbox69), eqb19, TRUE, TRUE, 0);
  gtk_scale_set_digits (GTK_SCALE (eqb19), 0);
  gtk_range_set_inverted (GTK_RANGE (eqb19), TRUE);

  label149 = gtk_label_new (_("1K5"));
  gtk_widget_set_name (label149, "label149");
  gtk_widget_show (label149);
  gtk_box_pack_start (GTK_BOX (vbox69), label149, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label149), GTK_JUSTIFY_LEFT);

  vbox70 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox70, "vbox70");
  gtk_widget_show (vbox70);
  gtk_box_pack_start (GTK_BOX (eqb_hbox), vbox70, TRUE, TRUE, 0);

  eqb20 = gtk_vscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -70, 24, 1, 6, 0)));
  gtk_widget_set_name (eqb20, "eqb20");
  gtk_widget_show (eqb20);
  gtk_box_pack_start (GTK_BOX (vbox70), eqb20, TRUE, TRUE, 0);
  gtk_scale_set_digits (GTK_SCALE (eqb20), 0);
  gtk_range_set_inverted (GTK_RANGE (eqb20), TRUE);

  label150 = gtk_label_new (_("2K"));
  gtk_widget_set_name (label150, "label150");
  gtk_widget_show (label150);
  gtk_box_pack_start (GTK_BOX (vbox70), label150, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label150), GTK_JUSTIFY_LEFT);

  vbox71 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox71, "vbox71");
  gtk_widget_show (vbox71);
  gtk_box_pack_start (GTK_BOX (eqb_hbox), vbox71, TRUE, TRUE, 0);

  eqb21 = gtk_vscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -70, 24, 1, 6, 0)));
  gtk_widget_set_name (eqb21, "eqb21");
  gtk_widget_show (eqb21);
  gtk_box_pack_start (GTK_BOX (vbox71), eqb21, TRUE, TRUE, 0);
  gtk_scale_set_digits (GTK_SCALE (eqb21), 0);
  gtk_range_set_inverted (GTK_RANGE (eqb21), TRUE);

  label151 = gtk_label_new (_("3K2"));
  gtk_widget_set_name (label151, "label151");
  gtk_widget_show (label151);
  gtk_box_pack_start (GTK_BOX (vbox71), label151, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label151), GTK_JUSTIFY_LEFT);

  vbox72 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox72, "vbox72");
  gtk_widget_show (vbox72);
  gtk_box_pack_start (GTK_BOX (eqb_hbox), vbox72, TRUE, TRUE, 0);

  eqb22 = gtk_vscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -70, 24, 1, 6, 0)));
  gtk_widget_set_name (eqb22, "eqb22");
  gtk_widget_show (eqb22);
  gtk_box_pack_start (GTK_BOX (vbox72), eqb22, TRUE, TRUE, 0);
  gtk_scale_set_digits (GTK_SCALE (eqb22), 0);
  gtk_range_set_inverted (GTK_RANGE (eqb22), TRUE);

  label152 = gtk_label_new (_("4K"));
  gtk_widget_set_name (label152, "label152");
  gtk_widget_show (label152);
  gtk_box_pack_start (GTK_BOX (vbox72), label152, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label152), GTK_JUSTIFY_LEFT);

  vbox73 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox73, "vbox73");
  gtk_widget_show (vbox73);
  gtk_box_pack_start (GTK_BOX (eqb_hbox), vbox73, TRUE, TRUE, 0);

  eqb23 = gtk_vscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -70, 24, 1, 6, 0)));
  gtk_widget_set_name (eqb23, "eqb23");
  gtk_widget_show (eqb23);
  gtk_box_pack_start (GTK_BOX (vbox73), eqb23, TRUE, TRUE, 0);
  gtk_scale_set_digits (GTK_SCALE (eqb23), 0);
  gtk_range_set_inverted (GTK_RANGE (eqb23), TRUE);

  label153 = gtk_label_new (_("5K"));
  gtk_widget_set_name (label153, "label153");
  gtk_widget_show (label153);
  gtk_box_pack_start (GTK_BOX (vbox73), label153, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label153), GTK_JUSTIFY_LEFT);

  vbox74 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox74, "vbox74");
  gtk_widget_show (vbox74);
  gtk_box_pack_start (GTK_BOX (eqb_hbox), vbox74, TRUE, TRUE, 0);

  eqb24 = gtk_vscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -70, 24, 1, 6, 0)));
  gtk_widget_set_name (eqb24, "eqb24");
  gtk_widget_show (eqb24);
  gtk_box_pack_start (GTK_BOX (vbox74), eqb24, TRUE, TRUE, 0);
  gtk_scale_set_digits (GTK_SCALE (eqb24), 0);
  gtk_range_set_inverted (GTK_RANGE (eqb24), TRUE);

  label154 = gtk_label_new (_("6K"));
  gtk_widget_set_name (label154, "label154");
  gtk_widget_show (label154);
  gtk_box_pack_start (GTK_BOX (vbox74), label154, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label154), GTK_JUSTIFY_LEFT);

  vbox75 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox75, "vbox75");
  gtk_widget_show (vbox75);
  gtk_box_pack_start (GTK_BOX (eqb_hbox), vbox75, TRUE, TRUE, 0);

  eqb25 = gtk_vscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -70, 24, 1, 6, 0)));
  gtk_widget_set_name (eqb25, "eqb25");
  gtk_widget_show (eqb25);
  gtk_box_pack_start (GTK_BOX (vbox75), eqb25, TRUE, TRUE, 0);
  gtk_scale_set_digits (GTK_SCALE (eqb25), 0);
  gtk_range_set_inverted (GTK_RANGE (eqb25), TRUE);

  label155 = gtk_label_new (_("8K"));
  gtk_widget_set_name (label155, "label155");
  gtk_widget_show (label155);
  gtk_box_pack_start (GTK_BOX (vbox75), label155, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label155), GTK_JUSTIFY_LEFT);

  vbox76 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox76, "vbox76");
  gtk_widget_show (vbox76);
  gtk_box_pack_start (GTK_BOX (eqb_hbox), vbox76, TRUE, TRUE, 0);

  eqb26 = gtk_vscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -70, 24, 1, 6, 0)));
  gtk_widget_set_name (eqb26, "eqb26");
  gtk_widget_show (eqb26);
  gtk_box_pack_start (GTK_BOX (vbox76), eqb26, TRUE, TRUE, 0);
  gtk_scale_set_digits (GTK_SCALE (eqb26), 0);
  gtk_range_set_inverted (GTK_RANGE (eqb26), TRUE);

  label156 = gtk_label_new (_("10K"));
  gtk_widget_set_name (label156, "label156");
  gtk_widget_show (label156);
  gtk_box_pack_start (GTK_BOX (vbox76), label156, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label156), GTK_JUSTIFY_LEFT);

  vbox77 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox77, "vbox77");
  gtk_widget_show (vbox77);
  gtk_box_pack_start (GTK_BOX (eqb_hbox), vbox77, TRUE, TRUE, 0);

  eqb27 = gtk_vscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -70, 24, 1, 6, 0)));
  gtk_widget_set_name (eqb27, "eqb27");
  gtk_widget_show (eqb27);
  gtk_box_pack_start (GTK_BOX (vbox77), eqb27, TRUE, TRUE, 0);
  gtk_scale_set_digits (GTK_SCALE (eqb27), 0);
  gtk_range_set_inverted (GTK_RANGE (eqb27), TRUE);

  label157 = gtk_label_new (_("12K"));
  gtk_widget_set_name (label157, "label157");
  gtk_widget_show (label157);
  gtk_box_pack_start (GTK_BOX (vbox77), label157, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label157), GTK_JUSTIFY_LEFT);

  vbox80 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox80, "vbox80");
  gtk_widget_show (vbox80);
  gtk_box_pack_start (GTK_BOX (eqb_hbox), vbox80, TRUE, TRUE, 0);

  eqb28 = gtk_vscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -70, 24, 1, 6, 0)));
  gtk_widget_set_name (eqb28, "eqb28");
  gtk_widget_show (eqb28);
  gtk_box_pack_start (GTK_BOX (vbox80), eqb28, TRUE, TRUE, 0);
  gtk_scale_set_digits (GTK_SCALE (eqb28), 0);
  gtk_range_set_inverted (GTK_RANGE (eqb28), TRUE);

  label158 = gtk_label_new (_("16K"));
  gtk_widget_set_name (label158, "label158");
  gtk_widget_show (label158);
  gtk_box_pack_start (GTK_BOX (vbox80), label158, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label158), GTK_JUSTIFY_LEFT);

  label47 = gtk_label_new (_("Faders"));
  gtk_widget_set_name (label47, "label47");
  gtk_widget_show (label47);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label47);
  gtk_label_set_justify (GTK_LABEL (label47), GTK_JUSTIFY_LEFT);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook1), empty_notebook_page);

  label48 = gtk_label_new (_("Graph"));
  gtk_widget_set_name (label48, "label48");
  gtk_widget_show (label48);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label48);
  gtk_label_set_justify (GTK_LABEL (label48), GTK_JUSTIFY_LEFT);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook1), empty_notebook_page);

  label49 = gtk_label_new (_("Parametric"));
  gtk_widget_set_name (label49, "label49");
  gtk_widget_show (label49);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label49);
  gtk_label_set_justify (GTK_LABEL (label49), GTK_JUSTIFY_LEFT);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook1), empty_notebook_page);

  label78 = gtk_label_new (_("Spectrum"));
  gtk_widget_set_name (label78, "label78");
  gtk_widget_show (label78);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), label78);
  gtk_label_set_justify (GTK_LABEL (label78), GTK_JUSTIFY_LEFT);

  cross_lbl = gtk_label_new (_("Crossover"));
  gtk_widget_set_name (cross_lbl, "cross_lbl");
  gtk_widget_show (cross_lbl);
  gtk_box_pack_start (GTK_BOX (vbox78), cross_lbl, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (cross_lbl), GTK_JUSTIFY_LEFT);

  low2mid = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (1230, 25, 20000, 10, 100, 0)));
  gtk_widget_set_name (low2mid, "low2mid");
  gtk_widget_show (low2mid);
  gtk_box_pack_start (GTK_BOX (vbox78), low2mid, FALSE, FALSE, 0);
  gtk_scale_set_value_pos (GTK_SCALE (low2mid), GTK_POS_LEFT);
  gtk_scale_set_digits (GTK_SCALE (low2mid), 0);

  mid2high = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (12500, 25, 20000, 10, 100, 0)));
  gtk_widget_set_name (mid2high, "mid2high");
  gtk_widget_show (mid2high);
  gtk_box_pack_start (GTK_BOX (vbox78), mid2high, FALSE, FALSE, 0);
  gtk_scale_set_value_pos (GTK_SCALE (mid2high), GTK_POS_LEFT);
  gtk_scale_set_digits (GTK_SCALE (mid2high), 0);

  alignment1 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment1, "alignment1");
  gtk_widget_show (alignment1);
  gtk_box_pack_start (GTK_BOX (vbox1), alignment1, TRUE, TRUE, 0);

  eventbox1 = gtk_event_box_new ();
  gtk_widget_set_name (eventbox1, "eventbox1");
  gtk_widget_show (eventbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), eventbox1);

  vbox11 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox11, "vbox11");
  gtk_widget_show (vbox11);
  gtk_container_add (GTK_CONTAINER (eventbox1), vbox11);

  frame2 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame2, "frame2");
  gtk_widget_show (frame2);
  gtk_box_pack_start (GTK_BOX (vbox11), frame2, TRUE, TRUE, 0);
  gtk_widget_set_size_request (frame2, 244, 260);

  vbox25 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox25, "vbox25");
  gtk_widget_show (vbox25);
  gtk_container_add (GTK_CONTAINER (frame2), vbox25);
  gtk_widget_set_size_request (vbox25, 600, -2);

  hbox15 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox15, "hbox15");
  gtk_widget_show (hbox15);
  gtk_box_pack_start (GTK_BOX (vbox25), hbox15, FALSE, TRUE, 0);

  hseparator3 = gtk_hseparator_new ();
  gtk_widget_set_name (hseparator3, "hseparator3");
  gtk_widget_show (hseparator3);
  gtk_box_pack_start (GTK_BOX (hbox15), hseparator3, TRUE, TRUE, 0);

  label62 = gtk_label_new (_("Compressors"));
  gtk_widget_set_name (label62, "label62");
  gtk_widget_show (label62);
  gtk_box_pack_start (GTK_BOX (hbox15), label62, FALSE, FALSE, 5);
  gtk_label_set_justify (GTK_LABEL (label62), GTK_JUSTIFY_LEFT);

  hseparator4 = gtk_hseparator_new ();
  gtk_widget_set_name (hseparator4, "hseparator4");
  gtk_widget_show (hseparator4);
  gtk_box_pack_start (GTK_BOX (hbox15), hseparator4, TRUE, TRUE, 0);

  hbox1 = gtk_hbox_new (TRUE, 13);
  gtk_widget_set_name (hbox1, "hbox1");
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox25), hbox1, TRUE, TRUE, 0);
  gtk_widget_set_size_request (hbox1, 605, -2);

  frame7 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame7, "frame7");
  gtk_widget_show (frame7);
  gtk_box_pack_start (GTK_BOX (hbox1), frame7, TRUE, TRUE, 0);
  gtk_widget_set_size_request (frame7, 215, -2);

  low_comp = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (low_comp, "low_comp");
  gtk_widget_show (low_comp);
  gtk_container_add (GTK_CONTAINER (frame7), low_comp);
  gtk_widget_set_size_request (low_comp, 205, -2);

  vbox30 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox30, "vbox30");
  gtk_widget_show (vbox30);
  gtk_box_pack_start (GTK_BOX (low_comp), vbox30, TRUE, TRUE, 0);

  table8 = gtk_table_new (2, 5, FALSE);
  gtk_widget_set_name (table8, "table8");
  gtk_widget_show (table8);
  gtk_box_pack_start (GTK_BOX (vbox30), table8, TRUE, TRUE, 0);
  gtk_table_set_col_spacings (GTK_TABLE (table8), 8);

  label71 = gtk_label_new (_("Release"));
  gtk_widget_set_name (label71, "label71");
  gtk_widget_show (label71);
  gtk_table_attach (GTK_TABLE (table8), label71, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label71, 45, -2);
  gtk_label_set_justify (GTK_LABEL (label71), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label71), 0, 0.5);

  label72 = gtk_label_new (_("Thresh"));
  gtk_widget_set_name (label72, "label72");
  gtk_widget_show (label72);
  gtk_table_attach (GTK_TABLE (table8), label72, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label72), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label72), 0, 0.5);

  label73 = gtk_label_new (_("Ratio"));
  gtk_widget_set_name (label73, "label73");
  gtk_widget_show (label73);
  gtk_table_attach (GTK_TABLE (table8), label73, 3, 4, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label73), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label73), 0, 0.5);

  vscale34 = gtk_vscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (10, 10, 400, 0, 0, 0)));
  gtk_widget_set_name (vscale34, "vscale34");
  gtk_widget_show (vscale34);
  gtk_table_attach (GTK_TABLE (table8), vscale34, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_range_set_inverted (GTK_RANGE (vscale34), TRUE);

  vscale35 = gtk_vscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (10, 10, 800, 0, 0, 0)));
  gtk_widget_set_name (vscale35, "vscale35");
  gtk_widget_show (vscale35);
  gtk_table_attach (GTK_TABLE (table8), vscale35, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_range_set_inverted (GTK_RANGE (vscale35), TRUE);

  vscale36 = gtk_vscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -30, 0, 0, 0, 0)));
  gtk_widget_set_name (vscale36, "vscale36");
  gtk_widget_show (vscale36);
  gtk_table_attach (GTK_TABLE (table8), vscale36, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_range_set_inverted (GTK_RANGE (vscale36), TRUE);

  vscale37 = gtk_vscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 0, 30, 0, 0, 0)));
  gtk_widget_set_name (vscale37, "vscale37");
  gtk_widget_show (vscale37);
  gtk_table_attach (GTK_TABLE (table8), vscale37, 4, 5, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_range_set_inverted (GTK_RANGE (vscale37), TRUE);

  vbox31 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox31, "vbox31");
  gtk_widget_show (vbox31);
  gtk_table_attach (GTK_TABLE (table8), vbox31, 3, 4, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  vscale38 = gtk_vscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (1, 1, 10, 0, 0, 0)));
  gtk_widget_set_name (vscale38, "vscale38");
  gtk_widget_show (vscale38);
  gtk_box_pack_start (GTK_BOX (vbox31), vscale38, TRUE, TRUE, 0);
  gtk_range_set_inverted (GTK_RANGE (vscale38), TRUE);

  label75 = gtk_label_new (_("Knee"));
  gtk_widget_set_name (label75, "label75");
  gtk_widget_show (label75);
  gtk_box_pack_start (GTK_BOX (vbox31), label75, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label75), GTK_JUSTIFY_LEFT);

  vscale39 = gtk_vscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 0, 1, 0, 0, 0)));
  gtk_widget_set_name (vscale39, "vscale39");
  gtk_widget_show (vscale39);
  gtk_box_pack_start (GTK_BOX (vbox31), vscale39, TRUE, TRUE, 0);
  gtk_range_set_inverted (GTK_RANGE (vscale39), TRUE);

  label70 = gtk_label_new (_("Attack"));
  gtk_widget_set_name (label70, "label70");
  gtk_widget_show (label70);
  gtk_table_attach (GTK_TABLE (table8), label70, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label70, 35, -2);
  gtk_label_set_justify (GTK_LABEL (label70), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label70), 0, 0.5);

  label74 = gtk_label_new (_("Makeup"));
  gtk_widget_set_name (label74, "label74");
  gtk_widget_show (label74);
  gtk_table_attach (GTK_TABLE (table8), label74, 4, 5, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label74), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label74), 0, 0.5);

  table9 = gtk_table_new (2, 2, FALSE);
  gtk_widget_set_name (table9, "table9");
  gtk_widget_show (table9);
  gtk_box_pack_start (GTK_BOX (low_comp), table9, TRUE, TRUE, 0);
  gtk_widget_set_size_request (table9, -2, 5);

  progressbar15 = gtk_progress_bar_new ();
  gtk_widget_set_name (progressbar15, "progressbar15");
  gtk_widget_show (progressbar15);
  gtk_table_attach (GTK_TABLE (table9), progressbar15, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (progressbar15, -2, 10);

  label76 = gtk_label_new (_("Level"));
  gtk_widget_set_name (label76, "label76");
  gtk_widget_show (label76);
  gtk_table_attach (GTK_TABLE (table9), label76, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 2, 0);
  gtk_widget_set_size_request (label76, -2, 14);
  gtk_label_set_justify (GTK_LABEL (label76), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label76), 0, 0.5);

  label77 = gtk_label_new (_("Gain"));
  gtk_widget_set_name (label77, "label77");
  gtk_widget_show (label77);
  gtk_table_attach (GTK_TABLE (table9), label77, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 2, 0);
  gtk_widget_set_size_request (label77, -2, 14);
  gtk_label_set_justify (GTK_LABEL (label77), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label77), 0, 0.5);

  progressbar14 = gtk_progress_bar_new ();
  gtk_widget_set_name (progressbar14, "progressbar14");
  gtk_widget_show (progressbar14);
  gtk_table_attach (GTK_TABLE (table9), progressbar14, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND), 0, 0);
  gtk_widget_set_size_request (progressbar14, -2, 10);

  label_Low = gtk_label_new (_("Low"));
  gtk_widget_set_name (label_Low, "label_Low");
  gtk_widget_show (label_Low);
  gtk_frame_set_label_widget (GTK_FRAME (frame7), label_Low);
  gtk_label_set_justify (GTK_LABEL (label_Low), GTK_JUSTIFY_LEFT);

  frame8 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame8, "frame8");
  gtk_widget_show (frame8);
  gtk_box_pack_start (GTK_BOX (hbox1), frame8, TRUE, TRUE, 0);
  gtk_widget_set_size_request (frame8, 215, -2);

  mid_comp = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (mid_comp, "mid_comp");
  gtk_widget_show (mid_comp);
  gtk_container_add (GTK_CONTAINER (frame8), mid_comp);
  gtk_widget_set_size_request (mid_comp, 205, -2);

  vbox36 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox36, "vbox36");
  gtk_widget_show (vbox36);
  gtk_box_pack_start (GTK_BOX (mid_comp), vbox36, TRUE, TRUE, 0);

  table12 = gtk_table_new (2, 5, FALSE);
  gtk_widget_set_name (table12, "table12");
  gtk_widget_show (table12);
  gtk_box_pack_start (GTK_BOX (vbox36), table12, TRUE, TRUE, 0);
  gtk_table_set_col_spacings (GTK_TABLE (table12), 8);

  label86 = gtk_label_new (_("Attack"));
  gtk_widget_set_name (label86, "label86");
  gtk_widget_show (label86);
  gtk_table_attach (GTK_TABLE (table12), label86, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label86), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label86), 0, 0.5);

  label87 = gtk_label_new (_("Release"));
  gtk_widget_set_name (label87, "label87");
  gtk_widget_show (label87);
  gtk_table_attach (GTK_TABLE (table12), label87, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label87), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label87), 0, 0.5);

  label88 = gtk_label_new (_("Thresh"));
  gtk_widget_set_name (label88, "label88");
  gtk_widget_show (label88);
  gtk_table_attach (GTK_TABLE (table12), label88, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label88), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label88), 0, 0.5);

  label89 = gtk_label_new (_("Ratio"));
  gtk_widget_set_name (label89, "label89");
  gtk_widget_show (label89);
  gtk_table_attach (GTK_TABLE (table12), label89, 3, 4, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label89), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label89), 0, 0.5);

  vscale43 = gtk_vscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (10, 10, 400, 0, 0, 0)));
  gtk_widget_set_name (vscale43, "vscale43");
  gtk_widget_show (vscale43);
  gtk_table_attach (GTK_TABLE (table12), vscale43, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_range_set_inverted (GTK_RANGE (vscale43), TRUE);

  vscale44 = gtk_vscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (10, 10, 800, 0, 0, 0)));
  gtk_widget_set_name (vscale44, "vscale44");
  gtk_widget_show (vscale44);
  gtk_table_attach (GTK_TABLE (table12), vscale44, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_range_set_inverted (GTK_RANGE (vscale44), TRUE);

  vscale45 = gtk_vscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -30, 0, 0, 0, 0)));
  gtk_widget_set_name (vscale45, "vscale45");
  gtk_widget_show (vscale45);
  gtk_table_attach (GTK_TABLE (table12), vscale45, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_range_set_inverted (GTK_RANGE (vscale45), TRUE);

  vscale46 = gtk_vscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 0, 30, 0, 0, 0)));
  gtk_widget_set_name (vscale46, "vscale46");
  gtk_widget_show (vscale46);
  gtk_table_attach (GTK_TABLE (table12), vscale46, 4, 5, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_range_set_inverted (GTK_RANGE (vscale46), TRUE);

  vbox37 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox37, "vbox37");
  gtk_widget_show (vbox37);
  gtk_table_attach (GTK_TABLE (table12), vbox37, 3, 4, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  vscale47 = gtk_vscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (1, 1, 10, 0, 0, 0)));
  gtk_widget_set_name (vscale47, "vscale47");
  gtk_widget_show (vscale47);
  gtk_box_pack_start (GTK_BOX (vbox37), vscale47, TRUE, TRUE, 0);
  gtk_range_set_inverted (GTK_RANGE (vscale47), TRUE);

  label91 = gtk_label_new (_("Knee"));
  gtk_widget_set_name (label91, "label91");
  gtk_widget_show (label91);
  gtk_box_pack_start (GTK_BOX (vbox37), label91, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label91), GTK_JUSTIFY_LEFT);

  vscale48 = gtk_vscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 0, 1, 0, 0, 0)));
  gtk_widget_set_name (vscale48, "vscale48");
  gtk_widget_show (vscale48);
  gtk_box_pack_start (GTK_BOX (vbox37), vscale48, TRUE, TRUE, 0);
  gtk_range_set_inverted (GTK_RANGE (vscale48), TRUE);

  label90 = gtk_label_new (_("Makeup"));
  gtk_widget_set_name (label90, "label90");
  gtk_widget_show (label90);
  gtk_table_attach (GTK_TABLE (table12), label90, 4, 5, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label90), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label90), 0, 0.5);

  table13 = gtk_table_new (2, 2, FALSE);
  gtk_widget_set_name (table13, "table13");
  gtk_widget_show (table13);
  gtk_box_pack_start (GTK_BOX (mid_comp), table13, TRUE, TRUE, 0);
  gtk_widget_set_size_request (table13, -2, 1);

  progressbar22 = gtk_progress_bar_new ();
  gtk_widget_set_name (progressbar22, "progressbar22");
  gtk_widget_show (progressbar22);
  gtk_table_attach (GTK_TABLE (table13), progressbar22, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (progressbar22, -2, 10);

  label92 = gtk_label_new (_("Level"));
  gtk_widget_set_name (label92, "label92");
  gtk_widget_show (label92);
  gtk_table_attach (GTK_TABLE (table13), label92, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 2, 0);
  gtk_widget_set_size_request (label92, -2, 14);
  gtk_label_set_justify (GTK_LABEL (label92), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label92), 0, 0.5);

  label93 = gtk_label_new (_("Gain"));
  gtk_widget_set_name (label93, "label93");
  gtk_widget_show (label93);
  gtk_table_attach (GTK_TABLE (table13), label93, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 2, 0);
  gtk_widget_set_size_request (label93, -2, 14);
  gtk_label_set_justify (GTK_LABEL (label93), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label93), 0, 0.5);

  progressbar23 = gtk_progress_bar_new ();
  gtk_widget_set_name (progressbar23, "progressbar23");
  gtk_widget_show (progressbar23);
  gtk_table_attach (GTK_TABLE (table13), progressbar23, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND), 0, 0);
  gtk_widget_set_size_request (progressbar23, -2, 10);

  label94 = gtk_label_new (_("Mid"));
  gtk_widget_set_name (label94, "label94");
  gtk_widget_show (label94);
  gtk_frame_set_label_widget (GTK_FRAME (frame8), label94);
  gtk_label_set_justify (GTK_LABEL (label94), GTK_JUSTIFY_LEFT);

  frame6 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame6, "frame6");
  gtk_widget_show (frame6);
  gtk_box_pack_start (GTK_BOX (hbox1), frame6, TRUE, TRUE, 0);
  gtk_widget_set_size_request (frame6, 215, -2);

  high_comp = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (high_comp, "high_comp");
  gtk_widget_show (high_comp);
  gtk_container_add (GTK_CONTAINER (frame6), high_comp);
  gtk_widget_set_size_request (high_comp, 205, -2);

  vbox18 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox18, "vbox18");
  gtk_widget_show (vbox18);
  gtk_box_pack_start (GTK_BOX (high_comp), vbox18, TRUE, TRUE, 0);

  table6 = gtk_table_new (2, 5, FALSE);
  gtk_widget_set_name (table6, "table6");
  gtk_widget_show (table6);
  gtk_box_pack_start (GTK_BOX (vbox18), table6, TRUE, TRUE, 0);
  gtk_table_set_col_spacings (GTK_TABLE (table6), 8);

  label22 = gtk_label_new (_("Attack"));
  gtk_widget_set_name (label22, "label22");
  gtk_widget_show (label22);
  gtk_table_attach (GTK_TABLE (table6), label22, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label22), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label22), 0, 0.5);

  label23 = gtk_label_new (_("Release"));
  gtk_widget_set_name (label23, "label23");
  gtk_widget_show (label23);
  gtk_table_attach (GTK_TABLE (table6), label23, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label23), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label23), 0, 0.5);

  label24 = gtk_label_new (_("Thresh"));
  gtk_widget_set_name (label24, "label24");
  gtk_widget_show (label24);
  gtk_table_attach (GTK_TABLE (table6), label24, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label24), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label24), 0, 0.5);

  label25 = gtk_label_new (_("Ratio"));
  gtk_widget_set_name (label25, "label25");
  gtk_widget_show (label25);
  gtk_table_attach (GTK_TABLE (table6), label25, 3, 4, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label25), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label25), 0, 0.5);

  vscale18 = gtk_vscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (10, 10, 400, 0, 0, 0)));
  gtk_widget_set_name (vscale18, "vscale18");
  gtk_widget_show (vscale18);
  gtk_table_attach (GTK_TABLE (table6), vscale18, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_range_set_inverted (GTK_RANGE (vscale18), TRUE);

  vscale19 = gtk_vscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (10, 10, 800, 0, 0, 0)));
  gtk_widget_set_name (vscale19, "vscale19");
  gtk_widget_show (vscale19);
  gtk_table_attach (GTK_TABLE (table6), vscale19, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_range_set_inverted (GTK_RANGE (vscale19), TRUE);

  vscale20 = gtk_vscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -30, 0, 0, 0, 0)));
  gtk_widget_set_name (vscale20, "vscale20");
  gtk_widget_show (vscale20);
  gtk_table_attach (GTK_TABLE (table6), vscale20, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_range_set_inverted (GTK_RANGE (vscale20), TRUE);

  vscale21 = gtk_vscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 0, 30, 0, 0, 0)));
  gtk_widget_set_name (vscale21, "vscale21");
  gtk_widget_show (vscale21);
  gtk_table_attach (GTK_TABLE (table6), vscale21, 4, 5, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_range_set_inverted (GTK_RANGE (vscale21), TRUE);

  vbox7 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox7, "vbox7");
  gtk_widget_show (vbox7);
  gtk_table_attach (GTK_TABLE (table6), vbox7, 3, 4, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  vscale22 = gtk_vscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (1, 1, 10, 0, 0, 0)));
  gtk_widget_set_name (vscale22, "vscale22");
  gtk_widget_show (vscale22);
  gtk_box_pack_start (GTK_BOX (vbox7), vscale22, TRUE, TRUE, 0);
  gtk_range_set_inverted (GTK_RANGE (vscale22), TRUE);

  label27 = gtk_label_new (_("Knee"));
  gtk_widget_set_name (label27, "label27");
  gtk_widget_show (label27);
  gtk_box_pack_start (GTK_BOX (vbox7), label27, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label27), GTK_JUSTIFY_LEFT);

  vscale23 = gtk_vscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 0, 1, 0, 0, 0)));
  gtk_widget_set_name (vscale23, "vscale23");
  gtk_widget_show (vscale23);
  gtk_box_pack_start (GTK_BOX (vbox7), vscale23, TRUE, TRUE, 0);
  gtk_range_set_inverted (GTK_RANGE (vscale23), TRUE);

  label26 = gtk_label_new (_("Makeup"));
  gtk_widget_set_name (label26, "label26");
  gtk_widget_show (label26);
  gtk_table_attach (GTK_TABLE (table6), label26, 4, 5, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label26), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label26), 0, 0.5);

  table11 = gtk_table_new (2, 2, FALSE);
  gtk_widget_set_name (table11, "table11");
  gtk_widget_show (table11);
  gtk_box_pack_start (GTK_BOX (high_comp), table11, TRUE, TRUE, 0);
  gtk_widget_set_size_request (table11, -2, 5);

  progressbar20 = gtk_progress_bar_new ();
  gtk_widget_set_name (progressbar20, "progressbar20");
  gtk_widget_show (progressbar20);
  gtk_table_attach (GTK_TABLE (table11), progressbar20, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (progressbar20, -2, 10);

  label84 = gtk_label_new (_("Level"));
  gtk_widget_set_name (label84, "label84");
  gtk_widget_show (label84);
  gtk_table_attach (GTK_TABLE (table11), label84, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 2, 0);
  gtk_widget_set_size_request (label84, -2, 14);
  gtk_label_set_justify (GTK_LABEL (label84), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label84), 0, 0.5);

  label85 = gtk_label_new (_("Gain"));
  gtk_widget_set_name (label85, "label85");
  gtk_widget_show (label85);
  gtk_table_attach (GTK_TABLE (table11), label85, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 2, 0);
  gtk_widget_set_size_request (label85, -2, 14);
  gtk_label_set_justify (GTK_LABEL (label85), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label85), 0, 0.5);

  progressbar21 = gtk_progress_bar_new ();
  gtk_widget_set_name (progressbar21, "progressbar21");
  gtk_widget_show (progressbar21);
  gtk_table_attach (GTK_TABLE (table11), progressbar21, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND), 0, 0);
  gtk_widget_set_size_request (progressbar21, -2, 10);

  label68 = gtk_label_new (_("High"));
  gtk_widget_set_name (label68, "label68");
  gtk_widget_show (label68);
  gtk_frame_set_label_widget (GTK_FRAME (frame6), label68);
  gtk_label_set_justify (GTK_LABEL (label68), GTK_JUSTIFY_LEFT);

  hbox7 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox7, "hbox7");
  gtk_widget_show (hbox7);
  gtk_box_pack_start (GTK_BOX (vbox11), hbox7, TRUE, TRUE, 3);
  gtk_widget_set_size_request (hbox7, -2, 195);

  curve1 = gtk_curve_new ();
  gtk_widget_set_name (curve1, "curve1");
  gtk_widget_show (curve1);
  gtk_box_pack_start (GTK_BOX (hbox7), curve1, TRUE, TRUE, 3);
  gtk_widget_set_size_request (curve1, 240, -2);
  gtk_curve_set_range (GTK_CURVE (curve1), 0, 1, 0, 1);

  vbox15 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox15, "vbox15");
  gtk_widget_show (vbox15);
  gtk_box_pack_start (GTK_BOX (hbox7), vbox15, FALSE, TRUE, 0);
  gtk_widget_set_size_request (vbox15, 453, -2);

  vbox12 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox12, "vbox12");
  gtk_widget_show (vbox12);
  gtk_box_pack_start (GTK_BOX (vbox15), vbox12, TRUE, TRUE, 4);
  gtk_widget_set_size_request (vbox12, 238, -2);

  hbox8 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox8, "hbox8");
  gtk_widget_show (hbox8);
  gtk_box_pack_start (GTK_BOX (vbox12), hbox8, TRUE, TRUE, 0);

  hbox_bottom_r = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox_bottom_r, "hbox_bottom_r");
  gtk_widget_show (hbox_bottom_r);
  gtk_box_pack_start (GTK_BOX (hbox8), hbox_bottom_r, TRUE, TRUE, 0);

  frame3 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame3, "frame3");
  gtk_widget_show (frame3);
  gtk_box_pack_start (GTK_BOX (hbox_bottom_r), frame3, TRUE, TRUE, 5);
  gtk_widget_set_size_request (frame3, 200, -2);

  vbox23 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox23, "vbox23");
  gtk_widget_show (vbox23);
  gtk_container_add (GTK_CONTAINER (frame3), vbox23);
  gtk_widget_set_size_request (vbox23, 286, 200);

  vbox_limiter = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox_limiter, "vbox_limiter");
  gtk_widget_show (vbox_limiter);
  gtk_box_pack_start (GTK_BOX (vbox23), vbox_limiter, TRUE, TRUE, 0);
  gtk_widget_set_size_request (vbox_limiter, -2, 123);

  hbox3 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox3, "hbox3");
  gtk_widget_show (hbox3);
  gtk_box_pack_start (GTK_BOX (vbox_limiter), hbox3, FALSE, FALSE, 0);
  gtk_widget_set_size_request (hbox3, -2, 15);

  hbox16 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox16, "hbox16");
  gtk_widget_show (hbox16);
  gtk_box_pack_start (GTK_BOX (hbox3), hbox16, TRUE, TRUE, 0);

  hseparator5 = gtk_hseparator_new ();
  gtk_widget_set_name (hseparator5, "hseparator5");
  gtk_widget_show (hseparator5);
  gtk_box_pack_start (GTK_BOX (hbox16), hseparator5, TRUE, TRUE, 0);
  gtk_widget_set_size_request (hseparator5, -2, 5);

  label63 = gtk_label_new (_("Limiter"));
  gtk_widget_set_name (label63, "label63");
  gtk_widget_show (label63);
  gtk_box_pack_start (GTK_BOX (hbox16), label63, FALSE, FALSE, 5);
  gtk_label_set_justify (GTK_LABEL (label63), GTK_JUSTIFY_LEFT);

  hseparator6 = gtk_hseparator_new ();
  gtk_widget_set_name (hseparator6, "hseparator6");
  gtk_widget_show (hseparator6);
  gtk_box_pack_start (GTK_BOX (hbox16), hseparator6, TRUE, TRUE, 0);
  gtk_widget_set_size_request (hseparator6, -2, 5);

  hbox10 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox10, "hbox10");
  gtk_widget_show (hbox10);
  gtk_box_pack_start (GTK_BOX (vbox_limiter), hbox10, TRUE, TRUE, 3);
  gtk_widget_set_size_request (hbox10, 286, -2);

  vbox32 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox32, "vbox32");
  gtk_widget_show (vbox32);
  gtk_box_pack_start (GTK_BOX (hbox10), vbox32, TRUE, TRUE, 0);

  label79 = gtk_label_new (_("Input"));
  gtk_widget_set_name (label79, "label79");
  gtk_widget_show (label79);
  gtk_box_pack_start (GTK_BOX (vbox32), label79, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label79), GTK_JUSTIFY_LEFT);

  hbox17 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox17, "hbox17");
  gtk_widget_show (hbox17);
  gtk_box_pack_start (GTK_BOX (vbox32), hbox17, TRUE, TRUE, 0);

  vscale40 = gtk_vscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (-10, 0, 0, 0, 0, 0)));
  gtk_widget_set_name (vscale40, "vscale40");
  gtk_widget_show (vscale40);
  gtk_box_pack_start (GTK_BOX (hbox17), vscale40, TRUE, TRUE, 0);
  gtk_range_set_inverted (GTK_RANGE (vscale40), TRUE);

  progressbar16 = gtk_progress_bar_new ();
  gtk_widget_set_name (progressbar16, "progressbar16");
  gtk_widget_show (progressbar16);
  gtk_box_pack_start (GTK_BOX (hbox17), progressbar16, FALSE, FALSE, 0);
  gtk_progress_bar_set_orientation (GTK_PROGRESS_BAR (progressbar16), GTK_PROGRESS_BOTTOM_TO_TOP);

  vbox33 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox33, "vbox33");
  gtk_widget_show (vbox33);
  gtk_box_pack_start (GTK_BOX (hbox10), vbox33, TRUE, TRUE, 0);

  label80 = gtk_label_new (_("Lookahead"));
  gtk_widget_set_name (label80, "label80");
  gtk_widget_show (label80);
  gtk_box_pack_start (GTK_BOX (vbox33), label80, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label80), GTK_JUSTIFY_LEFT);

  hbox18 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox18, "hbox18");
  gtk_widget_show (hbox18);
  gtk_box_pack_start (GTK_BOX (vbox33), hbox18, TRUE, TRUE, 0);

  vscale41 = gtk_vscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 0, 0, 0, 0, 0)));
  gtk_widget_set_name (vscale41, "vscale41");
  gtk_widget_show (vscale41);
  gtk_box_pack_start (GTK_BOX (hbox18), vscale41, TRUE, TRUE, 0);
  gtk_range_set_inverted (GTK_RANGE (vscale41), TRUE);

  vbox34 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox34, "vbox34");
  gtk_widget_show (vbox34);
  gtk_box_pack_start (GTK_BOX (hbox10), vbox34, TRUE, TRUE, 0);

  label81 = gtk_label_new (_("Output"));
  gtk_widget_set_name (label81, "label81");
  gtk_widget_show (label81);
  gtk_box_pack_start (GTK_BOX (vbox34), label81, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label81), GTK_JUSTIFY_LEFT);

  hbox19 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox19, "hbox19");
  gtk_widget_show (hbox19);
  gtk_box_pack_start (GTK_BOX (vbox34), hbox19, TRUE, TRUE, 0);

  vscale42 = gtk_vscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (-10, 0, 0, 0, 0, 0)));
  gtk_widget_set_name (vscale42, "vscale42");
  gtk_widget_show (vscale42);
  gtk_box_pack_start (GTK_BOX (hbox19), vscale42, TRUE, TRUE, 0);
  gtk_range_set_inverted (GTK_RANGE (vscale42), TRUE);

  progressbar17 = gtk_progress_bar_new ();
  gtk_widget_set_name (progressbar17, "progressbar17");
  gtk_widget_show (progressbar17);
  gtk_box_pack_start (GTK_BOX (hbox19), progressbar17, FALSE, FALSE, 5);
  gtk_progress_bar_set_orientation (GTK_PROGRESS_BAR (progressbar17), GTK_PROGRESS_BOTTOM_TO_TOP);

  vbuttonbox1 = gtk_vbutton_box_new ();
  gtk_widget_set_name (vbuttonbox1, "vbuttonbox1");
  gtk_widget_show (vbuttonbox1);
  gtk_box_pack_start (GTK_BOX (hbox_bottom_r), vbuttonbox1, TRUE, TRUE, 5);
  gtk_widget_set_size_request (vbuttonbox1, 85, 81);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (vbuttonbox1), GTK_BUTTONBOX_SPREAD);

  button8 = gtk_button_new_with_mnemonic (_("Load"));
  gtk_widget_set_name (button8, "button8");
  gtk_widget_show (button8);
  gtk_container_add (GTK_CONTAINER (vbuttonbox1), button8);
  GTK_WIDGET_SET_FLAGS (button8, GTK_CAN_DEFAULT);

  button9 = gtk_button_new_with_mnemonic (_("Save"));
  gtk_widget_set_name (button9, "button9");
  gtk_widget_show (button9);
  gtk_container_add (GTK_CONTAINER (vbuttonbox1), button9);
  GTK_WIDGET_SET_FLAGS (button9, GTK_CAN_DEFAULT);

  button10 = gtk_button_new_with_mnemonic (_("Help"));
  gtk_widget_set_name (button10, "button10");
  gtk_widget_show (button10);
  gtk_container_add (GTK_CONTAINER (vbuttonbox1), button10);
  GTK_WIDGET_SET_FLAGS (button10, GTK_CAN_DEFAULT);

  quit = gtk_button_new_with_mnemonic (_("Quit"));
  gtk_widget_set_name (quit, "quit");
  gtk_widget_show (quit);
  gtk_container_add (GTK_CONTAINER (vbuttonbox1), quit);
  GTK_WIDGET_SET_FLAGS (quit, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) window1, "delete_event",
                    G_CALLBACK (on_window1_delete_event),
                    NULL);
  g_signal_connect ((gpointer) in_trim_scale, "value_changed",
                    G_CALLBACK (on_in_trim_scale_value_changed),
                    NULL);
  g_signal_connect ((gpointer) low2mid, "value_changed",
                    G_CALLBACK (on_low2mid_value_changed),
                    NULL);
  g_signal_connect ((gpointer) low2mid, "realize",
                    G_CALLBACK (on_low2mid_realize),
                    NULL);
  g_signal_connect ((gpointer) mid2high, "value_changed",
                    G_CALLBACK (on_mid2high_value_changed),
                    NULL);
  g_signal_connect ((gpointer) mid2high, "realize",
                    G_CALLBACK (on_mid2high_realize),
                    NULL);
  g_signal_connect ((gpointer) low_comp, "realize",
                    G_CALLBACK (on_low_comp_realize),
                    NULL);
  g_signal_connect ((gpointer) mid_comp, "realize",
                    G_CALLBACK (on_mid_comp_realize),
                    NULL);
  g_signal_connect ((gpointer) high_comp, "realize",
                    G_CALLBACK (on_high_comp_realize),
                    NULL);
  g_signal_connect ((gpointer) quit, "clicked",
                    G_CALLBACK (on_quit_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (window1, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (window1, vbox8, "vbox8");
  GLADE_HOOKUP_OBJECT (window1, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (window1, vbox19, "vbox19");
  GLADE_HOOKUP_OBJECT (window1, vbox24, "vbox24");
  GLADE_HOOKUP_OBJECT (window1, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (window1, vbox24_2, "vbox24_2");
  GLADE_HOOKUP_OBJECT (window1, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (window1, in_trim_scale, "in_trim_scale");
  GLADE_HOOKUP_OBJECT (window1, inmeter, "inmeter");
  GLADE_HOOKUP_OBJECT (window1, label61, "label61");
  GLADE_HOOKUP_OBJECT (window1, vbox78, "vbox78");
  GLADE_HOOKUP_OBJECT (window1, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (window1, hbox21, "hbox21");
  GLADE_HOOKUP_OBJECT (window1, eqb_hbox, "eqb_hbox");
  GLADE_HOOKUP_OBJECT (window1, vbox41, "vbox41");
  GLADE_HOOKUP_OBJECT (window1, eqb1, "eqb1");
  GLADE_HOOKUP_OBJECT (window1, label131, "label131");
  GLADE_HOOKUP_OBJECT (window1, vbox42, "vbox42");
  GLADE_HOOKUP_OBJECT (window1, vbox52, "vbox52");
  GLADE_HOOKUP_OBJECT (window1, eqb2, "eqb2");
  GLADE_HOOKUP_OBJECT (window1, label132, "label132");
  GLADE_HOOKUP_OBJECT (window1, vbox43, "vbox43");
  GLADE_HOOKUP_OBJECT (window1, vbox53, "vbox53");
  GLADE_HOOKUP_OBJECT (window1, eqb3, "eqb3");
  GLADE_HOOKUP_OBJECT (window1, label133, "label133");
  GLADE_HOOKUP_OBJECT (window1, vbox44, "vbox44");
  GLADE_HOOKUP_OBJECT (window1, vbox54, "vbox54");
  GLADE_HOOKUP_OBJECT (window1, eqb4, "eqb4");
  GLADE_HOOKUP_OBJECT (window1, label134, "label134");
  GLADE_HOOKUP_OBJECT (window1, vbox45, "vbox45");
  GLADE_HOOKUP_OBJECT (window1, vbox55, "vbox55");
  GLADE_HOOKUP_OBJECT (window1, eqb5, "eqb5");
  GLADE_HOOKUP_OBJECT (window1, label135, "label135");
  GLADE_HOOKUP_OBJECT (window1, vbox46, "vbox46");
  GLADE_HOOKUP_OBJECT (window1, vbox56, "vbox56");
  GLADE_HOOKUP_OBJECT (window1, eqb6, "eqb6");
  GLADE_HOOKUP_OBJECT (window1, label136, "label136");
  GLADE_HOOKUP_OBJECT (window1, vbox47, "vbox47");
  GLADE_HOOKUP_OBJECT (window1, vbox57, "vbox57");
  GLADE_HOOKUP_OBJECT (window1, eqb7, "eqb7");
  GLADE_HOOKUP_OBJECT (window1, label137, "label137");
  GLADE_HOOKUP_OBJECT (window1, vbox48, "vbox48");
  GLADE_HOOKUP_OBJECT (window1, vbox58, "vbox58");
  GLADE_HOOKUP_OBJECT (window1, eqb8, "eqb8");
  GLADE_HOOKUP_OBJECT (window1, label138, "label138");
  GLADE_HOOKUP_OBJECT (window1, vbox50, "vbox50");
  GLADE_HOOKUP_OBJECT (window1, vbox59, "vbox59");
  GLADE_HOOKUP_OBJECT (window1, eqb9, "eqb9");
  GLADE_HOOKUP_OBJECT (window1, label139, "label139");
  GLADE_HOOKUP_OBJECT (window1, vbox49, "vbox49");
  GLADE_HOOKUP_OBJECT (window1, vbox60, "vbox60");
  GLADE_HOOKUP_OBJECT (window1, eqb10, "eqb10");
  GLADE_HOOKUP_OBJECT (window1, label140, "label140");
  GLADE_HOOKUP_OBJECT (window1, vbox51, "vbox51");
  GLADE_HOOKUP_OBJECT (window1, vbox61, "vbox61");
  GLADE_HOOKUP_OBJECT (window1, eqb11, "eqb11");
  GLADE_HOOKUP_OBJECT (window1, label141, "label141");
  GLADE_HOOKUP_OBJECT (window1, vbox62, "vbox62");
  GLADE_HOOKUP_OBJECT (window1, eqb12, "eqb12");
  GLADE_HOOKUP_OBJECT (window1, label142, "label142");
  GLADE_HOOKUP_OBJECT (window1, vbox63, "vbox63");
  GLADE_HOOKUP_OBJECT (window1, eqb13, "eqb13");
  GLADE_HOOKUP_OBJECT (window1, label143, "label143");
  GLADE_HOOKUP_OBJECT (window1, vbox64, "vbox64");
  GLADE_HOOKUP_OBJECT (window1, eqb14, "eqb14");
  GLADE_HOOKUP_OBJECT (window1, label144, "label144");
  GLADE_HOOKUP_OBJECT (window1, vbox65, "vbox65");
  GLADE_HOOKUP_OBJECT (window1, eqb15, "eqb15");
  GLADE_HOOKUP_OBJECT (window1, label145, "label145");
  GLADE_HOOKUP_OBJECT (window1, vbox66, "vbox66");
  GLADE_HOOKUP_OBJECT (window1, eqb16, "eqb16");
  GLADE_HOOKUP_OBJECT (window1, label146, "label146");
  GLADE_HOOKUP_OBJECT (window1, vbox67, "vbox67");
  GLADE_HOOKUP_OBJECT (window1, eqb17, "eqb17");
  GLADE_HOOKUP_OBJECT (window1, label147, "label147");
  GLADE_HOOKUP_OBJECT (window1, vbox68, "vbox68");
  GLADE_HOOKUP_OBJECT (window1, eqb18, "eqb18");
  GLADE_HOOKUP_OBJECT (window1, label148, "label148");
  GLADE_HOOKUP_OBJECT (window1, vbox69, "vbox69");
  GLADE_HOOKUP_OBJECT (window1, eqb19, "eqb19");
  GLADE_HOOKUP_OBJECT (window1, label149, "label149");
  GLADE_HOOKUP_OBJECT (window1, vbox70, "vbox70");
  GLADE_HOOKUP_OBJECT (window1, eqb20, "eqb20");
  GLADE_HOOKUP_OBJECT (window1, label150, "label150");
  GLADE_HOOKUP_OBJECT (window1, vbox71, "vbox71");
  GLADE_HOOKUP_OBJECT (window1, eqb21, "eqb21");
  GLADE_HOOKUP_OBJECT (window1, label151, "label151");
  GLADE_HOOKUP_OBJECT (window1, vbox72, "vbox72");
  GLADE_HOOKUP_OBJECT (window1, eqb22, "eqb22");
  GLADE_HOOKUP_OBJECT (window1, label152, "label152");
  GLADE_HOOKUP_OBJECT (window1, vbox73, "vbox73");
  GLADE_HOOKUP_OBJECT (window1, eqb23, "eqb23");
  GLADE_HOOKUP_OBJECT (window1, label153, "label153");
  GLADE_HOOKUP_OBJECT (window1, vbox74, "vbox74");
  GLADE_HOOKUP_OBJECT (window1, eqb24, "eqb24");
  GLADE_HOOKUP_OBJECT (window1, label154, "label154");
  GLADE_HOOKUP_OBJECT (window1, vbox75, "vbox75");
  GLADE_HOOKUP_OBJECT (window1, eqb25, "eqb25");
  GLADE_HOOKUP_OBJECT (window1, label155, "label155");
  GLADE_HOOKUP_OBJECT (window1, vbox76, "vbox76");
  GLADE_HOOKUP_OBJECT (window1, eqb26, "eqb26");
  GLADE_HOOKUP_OBJECT (window1, label156, "label156");
  GLADE_HOOKUP_OBJECT (window1, vbox77, "vbox77");
  GLADE_HOOKUP_OBJECT (window1, eqb27, "eqb27");
  GLADE_HOOKUP_OBJECT (window1, label157, "label157");
  GLADE_HOOKUP_OBJECT (window1, vbox80, "vbox80");
  GLADE_HOOKUP_OBJECT (window1, eqb28, "eqb28");
  GLADE_HOOKUP_OBJECT (window1, label158, "label158");
  GLADE_HOOKUP_OBJECT (window1, label47, "label47");
  GLADE_HOOKUP_OBJECT (window1, label48, "label48");
  GLADE_HOOKUP_OBJECT (window1, label49, "label49");
  GLADE_HOOKUP_OBJECT (window1, label78, "label78");
  GLADE_HOOKUP_OBJECT (window1, cross_lbl, "cross_lbl");
  GLADE_HOOKUP_OBJECT (window1, low2mid, "low2mid");
  GLADE_HOOKUP_OBJECT (window1, mid2high, "mid2high");
  GLADE_HOOKUP_OBJECT (window1, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (window1, eventbox1, "eventbox1");
  GLADE_HOOKUP_OBJECT (window1, vbox11, "vbox11");
  GLADE_HOOKUP_OBJECT (window1, frame2, "frame2");
  GLADE_HOOKUP_OBJECT (window1, vbox25, "vbox25");
  GLADE_HOOKUP_OBJECT (window1, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (window1, hseparator3, "hseparator3");
  GLADE_HOOKUP_OBJECT (window1, label62, "label62");
  GLADE_HOOKUP_OBJECT (window1, hseparator4, "hseparator4");
  GLADE_HOOKUP_OBJECT (window1, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (window1, frame7, "frame7");
  GLADE_HOOKUP_OBJECT (window1, low_comp, "low_comp");
  GLADE_HOOKUP_OBJECT (window1, vbox30, "vbox30");
  GLADE_HOOKUP_OBJECT (window1, table8, "table8");
  GLADE_HOOKUP_OBJECT (window1, label71, "label71");
  GLADE_HOOKUP_OBJECT (window1, label72, "label72");
  GLADE_HOOKUP_OBJECT (window1, label73, "label73");
  GLADE_HOOKUP_OBJECT (window1, vscale34, "vscale34");
  GLADE_HOOKUP_OBJECT (window1, vscale35, "vscale35");
  GLADE_HOOKUP_OBJECT (window1, vscale36, "vscale36");
  GLADE_HOOKUP_OBJECT (window1, vscale37, "vscale37");
  GLADE_HOOKUP_OBJECT (window1, vbox31, "vbox31");
  GLADE_HOOKUP_OBJECT (window1, vscale38, "vscale38");
  GLADE_HOOKUP_OBJECT (window1, label75, "label75");
  GLADE_HOOKUP_OBJECT (window1, vscale39, "vscale39");
  GLADE_HOOKUP_OBJECT (window1, label70, "label70");
  GLADE_HOOKUP_OBJECT (window1, label74, "label74");
  GLADE_HOOKUP_OBJECT (window1, table9, "table9");
  GLADE_HOOKUP_OBJECT (window1, progressbar15, "progressbar15");
  GLADE_HOOKUP_OBJECT (window1, label76, "label76");
  GLADE_HOOKUP_OBJECT (window1, label77, "label77");
  GLADE_HOOKUP_OBJECT (window1, progressbar14, "progressbar14");
  GLADE_HOOKUP_OBJECT (window1, label_Low, "label_Low");
  GLADE_HOOKUP_OBJECT (window1, frame8, "frame8");
  GLADE_HOOKUP_OBJECT (window1, mid_comp, "mid_comp");
  GLADE_HOOKUP_OBJECT (window1, vbox36, "vbox36");
  GLADE_HOOKUP_OBJECT (window1, table12, "table12");
  GLADE_HOOKUP_OBJECT (window1, label86, "label86");
  GLADE_HOOKUP_OBJECT (window1, label87, "label87");
  GLADE_HOOKUP_OBJECT (window1, label88, "label88");
  GLADE_HOOKUP_OBJECT (window1, label89, "label89");
  GLADE_HOOKUP_OBJECT (window1, vscale43, "vscale43");
  GLADE_HOOKUP_OBJECT (window1, vscale44, "vscale44");
  GLADE_HOOKUP_OBJECT (window1, vscale45, "vscale45");
  GLADE_HOOKUP_OBJECT (window1, vscale46, "vscale46");
  GLADE_HOOKUP_OBJECT (window1, vbox37, "vbox37");
  GLADE_HOOKUP_OBJECT (window1, vscale47, "vscale47");
  GLADE_HOOKUP_OBJECT (window1, label91, "label91");
  GLADE_HOOKUP_OBJECT (window1, vscale48, "vscale48");
  GLADE_HOOKUP_OBJECT (window1, label90, "label90");
  GLADE_HOOKUP_OBJECT (window1, table13, "table13");
  GLADE_HOOKUP_OBJECT (window1, progressbar22, "progressbar22");
  GLADE_HOOKUP_OBJECT (window1, label92, "label92");
  GLADE_HOOKUP_OBJECT (window1, label93, "label93");
  GLADE_HOOKUP_OBJECT (window1, progressbar23, "progressbar23");
  GLADE_HOOKUP_OBJECT (window1, label94, "label94");
  GLADE_HOOKUP_OBJECT (window1, frame6, "frame6");
  GLADE_HOOKUP_OBJECT (window1, high_comp, "high_comp");
  GLADE_HOOKUP_OBJECT (window1, vbox18, "vbox18");
  GLADE_HOOKUP_OBJECT (window1, table6, "table6");
  GLADE_HOOKUP_OBJECT (window1, label22, "label22");
  GLADE_HOOKUP_OBJECT (window1, label23, "label23");
  GLADE_HOOKUP_OBJECT (window1, label24, "label24");
  GLADE_HOOKUP_OBJECT (window1, label25, "label25");
  GLADE_HOOKUP_OBJECT (window1, vscale18, "vscale18");
  GLADE_HOOKUP_OBJECT (window1, vscale19, "vscale19");
  GLADE_HOOKUP_OBJECT (window1, vscale20, "vscale20");
  GLADE_HOOKUP_OBJECT (window1, vscale21, "vscale21");
  GLADE_HOOKUP_OBJECT (window1, vbox7, "vbox7");
  GLADE_HOOKUP_OBJECT (window1, vscale22, "vscale22");
  GLADE_HOOKUP_OBJECT (window1, label27, "label27");
  GLADE_HOOKUP_OBJECT (window1, vscale23, "vscale23");
  GLADE_HOOKUP_OBJECT (window1, label26, "label26");
  GLADE_HOOKUP_OBJECT (window1, table11, "table11");
  GLADE_HOOKUP_OBJECT (window1, progressbar20, "progressbar20");
  GLADE_HOOKUP_OBJECT (window1, label84, "label84");
  GLADE_HOOKUP_OBJECT (window1, label85, "label85");
  GLADE_HOOKUP_OBJECT (window1, progressbar21, "progressbar21");
  GLADE_HOOKUP_OBJECT (window1, label68, "label68");
  GLADE_HOOKUP_OBJECT (window1, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (window1, curve1, "curve1");
  GLADE_HOOKUP_OBJECT (window1, vbox15, "vbox15");
  GLADE_HOOKUP_OBJECT (window1, vbox12, "vbox12");
  GLADE_HOOKUP_OBJECT (window1, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (window1, hbox_bottom_r, "hbox_bottom_r");
  GLADE_HOOKUP_OBJECT (window1, frame3, "frame3");
  GLADE_HOOKUP_OBJECT (window1, vbox23, "vbox23");
  GLADE_HOOKUP_OBJECT (window1, vbox_limiter, "vbox_limiter");
  GLADE_HOOKUP_OBJECT (window1, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (window1, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (window1, hseparator5, "hseparator5");
  GLADE_HOOKUP_OBJECT (window1, label63, "label63");
  GLADE_HOOKUP_OBJECT (window1, hseparator6, "hseparator6");
  GLADE_HOOKUP_OBJECT (window1, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (window1, vbox32, "vbox32");
  GLADE_HOOKUP_OBJECT (window1, label79, "label79");
  GLADE_HOOKUP_OBJECT (window1, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (window1, vscale40, "vscale40");
  GLADE_HOOKUP_OBJECT (window1, progressbar16, "progressbar16");
  GLADE_HOOKUP_OBJECT (window1, vbox33, "vbox33");
  GLADE_HOOKUP_OBJECT (window1, label80, "label80");
  GLADE_HOOKUP_OBJECT (window1, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (window1, vscale41, "vscale41");
  GLADE_HOOKUP_OBJECT (window1, vbox34, "vbox34");
  GLADE_HOOKUP_OBJECT (window1, label81, "label81");
  GLADE_HOOKUP_OBJECT (window1, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (window1, vscale42, "vscale42");
  GLADE_HOOKUP_OBJECT (window1, progressbar17, "progressbar17");
  GLADE_HOOKUP_OBJECT (window1, vbuttonbox1, "vbuttonbox1");
  GLADE_HOOKUP_OBJECT (window1, button8, "button8");
  GLADE_HOOKUP_OBJECT (window1, button9, "button9");
  GLADE_HOOKUP_OBJECT (window1, button10, "button10");
  GLADE_HOOKUP_OBJECT (window1, quit, "quit");

  return window1;
}

