/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window1 (void);
GtkWidget* create_scene_menu (void);
GtkWidget* create_eq_options_dialog (void);
GtkWidget* create_preferences_dialog (void);
GtkWidget* create_colorselectiondialog1 (void);
GtkWidget* create_scene_name_dialog (void);
GtkWidget* create_filter_tuning (void);
