.TH "JAMin" "1" "0.5.39" "December 2003" "Audio"
.SH "NAME"
jamin \- JACK Audio Mastering interface
.SH "SYNOPSIS"
\fBjamin\fR [\-hdFTtvV] [inport1 inport2 [outport1 outport2]]
.SH "DESCRIPTION"
\fBJAMin\fR is the \fBJACK\fR (JACK Audio Connection Kit) Audio Mastering interface.

\fBJAMin\fR is designed to perform professional audio mastering of any number of input streams.  It consists of a number of tools to do this: a 1024 band hand drawn EQ with modifiable parametric controls, a 31 band graphic EQ, 3 band compressor, 3 band stereo width control, lookahead limiter, boost, and a number of other features.

For the latest \fBJAMin\fR information, please consult the web site,
<\fBhttp://jamin.sourceforge.net\fR>.
.SH "OPTIONS"
.TP 
\fB\-h, \-\-help\fR
.br 
Print a brief usage message describing the main \fBjamin\fR options.
.TP 
\fB\-d\fR
.br 
Dummy mode, start jamin without a JACK server (jackd) running.  For testing
purposes.
.TP 
\fB\-F\fR
.br 
Make all errors fatal.
.TP 
\fB\-T\fR
.br 
List trace output.
.TP 
\fB\-t\fR
.br 
No DSP thread.
.TP 
\fB\-v\fR
.br 
verbose.
.TP 
\fB\-V\fR
Output version and quit.
.SH "EXAMPLES"
.PP 
Since \fBJAMin\fR is not a standalone program we need to run a number of other programs to provide input audio data and receive the modified/mastered output audio data.  \fBJAMin\fR requires \fBJACK\fR (except in dummy mode) and, at the very least, something to feed it the audio data.  The following is an example of a test run using \fBjackd\fR and \fBalsaplayer\fR.  The output will go to the standard pcm outs on your system:
.IP 
jackd \-R \-d alsa \-d ice1712 \-n 2 \-p 2048 \-r 48000 &
.br 
alsaplayer \-s src \-S \-o jack song.wav &
.br 
jamin src:out_1 src:out_2 alsa_pcm:playback_1 alsa_pcm:playback_2
.br 
.PP 
The above example uses an ice1712 chipset card driver.  If you have a card with that chipset you might also want to run \fBenvy24control\fR (from the \fBALSA\fR package).  Other cards will require different drivers.  This is the brute force method of running \fBJAMin\fR.  A much better way is to use \fBqjackctl\fR to start \fBJACK\fR and handle all of the connections.  After starting \fBjackd\fR using \fBqjackctl\fR you can run \fBalsaplayer\fR and then \fBJAMin\fR.
.br 
.IP 
qjackctl &
.br 
alsaplayer \-o jack song.wav &
.br 
jamin
.PP 
Any \fBJACK\fR aware player, such as \fBRezound\fR, can be used to feed \fBJAMin\fR.  An interesting variation on using different applications for the player and recorder is to use \fBArdour\fR as the source \fIand\fR destination for \fBJAMin\fR.  In \fBArdour\fR run all of your track outputs into a stereo audio bus, run the bus outs into \fBJAMin\fR, then run the \fBJAMin\fR outs back into a record enabled \fBArdour\fR stereo track.  Somewhat bizarre but it gives you some interesting capabilities.  You can mix and master at the same time.

.SH "SEE ALSO:"
.BR <\fBhttp://jamin.sourceforge.net\fR>
.br 
.BR <\fBhttp://www.alsa\-project.org\fR>
.br 
.BR <\fBhttp://jackd.sourceforge.net\fR>
.br 
.BR <\fBhttp://qjackctl.sourceforge.net\fR>
.br 
.BR <\fBhttp://www.suse.de/~mana/jack.html\fR>
.br 
.BR <\fBhttp://alsaplayer.sourceforge.net\fR>
.br 
.BR <\fBhttp://ardour.sourceforge.net\fR>
.br 
.BR <\fBhttp://rezound.sourceforge.net\fR>
.br 
.BR jackd(1)
.br 
.BR alsaplayer(1)
.br 
.BR ardour(1)
.SH "BUGS"
Please send bug reports to <\fBjamin\-devel@lists.sourceforge.net\fR>.
.SH "AUTHORS"
Steve Harris is the JAMin principle author and team leader.  SourceForge CVS developers, in alphabetical order:
.IP 
.br 
Jan Depner
.br 
Steve Harris
.br 
Jack O'Quin
.br 
Ron Parker
.br 
Patrick Shirkey
.PP 
